version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - web
    depends_on:
      - db


  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - web
    depends_on:
      - app
    labels:
      - "traefik.enable=false"

volumes:
  dbdata:

networks:
  web:
    driver: bridge